import type { TechStackItem } from "./types";

export const techStack: TechStackItem[] = [
  { label: "JavaScript", icon: "javascript.svg" },
  { label: "React", icon: "react.svg" },
  { label: "Next.js", icon: "next-js.svg" },
  { label: "Node.js", icon: "node-js.svg" },
  { label: "Express.js", icon: "express.svg" },
  { label: "NestJS", icon: "nest.svg" },
  { label: "GraphQL", icon: "graphql.svg" },
  { label: "TypeScript", icon: "typescript.svg" },
  { label: "Hasura", icon: "hasura.svg" },
  { label: "MongoDB", icon: "mongodb.svg" },
  { label: "Redux", icon: "redux.svg" },
  { label: "PostgreSQL", icon: "postgresql.svg" },
  { label: "Jest", icon: "jest.svg" },
  { label: "Apollo", icon: "graphql.svg" },
  { label: "Cypress", icon: "cypress.svg" },
  { label: "Material UI", icon: "material-ui.svg" },
  { label: "Ant Design", icon: "ant-design.svg" },
  { label: "Styled Components", icon: "styled-components.svg" },
  { label: "Webpack", icon: "webpack.svg" },
  { label: "Rollup", icon: "rollup.svg" },
  { label: "Turborepo", icon: "vercel.svg" },
  { label: "Yarn Workspaces", icon: "yarn.svg" },
  { label: "Storybook", icon: "storybook.svg" },
  { label: "Biome", icon: "hasura.svg" },
  { label: "Git", icon: "git.svg" },
  { label: "GitHub Actions", icon: "github.svg" },
  { label: "React Native", icon: "react.svg" },
];
